### PR TITLE
Refactor Function definitions to be type preserving and GPU compatibly

### PR DESCRIPTION
**Pull request by dominic-chang**
Refactored most of the code to be type preserving so that It can work with `CUDA.jl` and `Metal.jl`.

### CODE REVIEW

**Comment by dominic-chang** [comment]
I also own the [`JacobiEllitpic.jl`](https://github.com/dchang10/JacobiElliptic.jl/) repo. This is an implementation of algorithms for [Elliptic integrals by Toshio Fukushima](https://ieeexplore.ieee.org/document/7203795). I think it might be good to merge these into a single repo for convenience. Let me know what you think.

**Comment by archermarx** [comment]
Thanks for the PR. Merging the repos, or even just deprecating this one, would be fine with me. I only created this repo so that I could register [LoopFieldCalc](https://github.com/archermarx/LoopFieldCalc.jl). In the end, I just moved whatever needed functionality from this repo directly into that one, so this repo is kind of purposeless beyond being a marginal improvement in Elliptic.jl

**Comment by archermarx** [comment]
Which option (deprecation/merge) would you prefer? Your JacobiElliptic looks like a nice package, and I like your focus on GPU compatability

**Comment by dominic-chang** [comment]
Sure, I think I might work on merging the repo's, partly because I think a name like `JacobiElliptic` is more descriptive than `Elliptic2` and also because I'd like to analytically continue the domain of validity of these algorithms.

**Comment by dominic-chang** [comment]
> Which option (deprecation/merge) would you prefer? Your JacobiElliptic looks like a nice package, and I like your focus on GPU compatability

I'm not sure I understand what the difference is

**Comment by archermarx** [comment]
> I'm not sure I understand what the difference is

You know, I don't think there is one. I think merging the two repos sounds like a great idea. I could then also update my magnetic field code to rely on JacobiElliptic.jl which would be awesome and pave the way for that working on GPUs.

**Comment by dominic-chang** [comment]
> > I'm not sure I understand what the difference is
> 
> You know, I don't think there is one. I think merging the two repos sounds like a great idea. I could then also update my magnetic field code to rely on JacobiElliptic.jl which would be awesome and pave the way for that working on GPUs.

Great! I'll do that then. Thanks

**Comment by dominic-chang** [comment]
Can I add you as a developer on that project? No pressure if you'd rather not help maintain it

**Comment by archermarx** [comment]
Yeah, sure!

**Pull request merged**
